# Derivatives Module Demonstrations

This notebook showcases the full capabilities of the `lab_math_tools.derivatives` module:
- **`derivative`**: Central-difference numerical derivative for scalar ($\mathbb{R} \to \mathbb{R}$) and vector-valued ($\mathbb{R} \to \mathbb{R}^n$) functions.
- **`partial_derivative`**: Partial derivative of multivariate scalar or vector-valued functions ($\mathbb{R}^n \to \mathbb{R}$ or $\mathbb{R}^n \to \mathbb{R}^m$) with respect to a chosen variable.
- **`v_gradient`**: Full gradient vector $\nabla f$ of a scalar-valued multivariate function ($\mathbb{R}^n \to \mathbb{R}$).
- **`divergence`**: Scalar divergence $\nabla \cdot \mathbf{f}$ of a vector field ($\mathbb{R}^n \to \mathbb{R}^n$).

All functions use the **Simple Approximation At Point (saap)** central-difference formula:
$$f'(x) \approx \frac{f(x+h) - f(x-h)}{2h} \quad O(h^2)$$


In [14]:
# Imports
import numpy as np
from lab_math_tools.derivatives import (
    derivative,
    partial_derivative,
    v_gradient,
    divergence,
)


---
## 1. `derivative` — Scalar Functions ($\mathbb{R} \to \mathbb{R}$)

For a function $f : \mathbb{R} \to \mathbb{R}$, `derivative(f, x, h)` computes $f'(x)$ using the central-difference formula with step size $h$ (default `1e-5`).

### 1.1 Polynomial: $f(x) = x^2$
The exact derivative is $f'(x) = 2x$, so at $x = 3.0$ we expect $6.0$.


In [15]:
f = lambda x: x**2

x0 = 3.0
numerical = derivative(f, x0)
exact     = 2 * x0

print(f"f(x) = x^2  at  x = {x0}")
print(f"  Numerical : {numerical:.8f}")
print(f"  Exact     : {exact:.8f}")
print(f"  Error     : {abs(numerical - exact):.2e}")


f(x) = x^2  at  x = 3.0
  Numerical : 6.00000000
  Exact     : 6.00000000
  Error     : 3.93e-11


### 1.2 Trigonometric: $f(x) = \sin(x)$
The exact derivative is $f'(x) = \cos(x)$, so at $x = \pi/4$ we expect $\cos(\pi/4) = \frac{\sqrt{2}}{2} \approx 0.70711$.


In [16]:
x0 = np.pi / 4
numerical = derivative(np.sin, x0)
exact     = np.cos(x0)

print(f"f(x) = sin(x)  at  x = pi/4")
print(f"  Numerical : {numerical:.8f}")
print(f"  Exact     : {exact:.8f}")
print(f"  Error     : {abs(numerical - exact):.2e}")


f(x) = sin(x)  at  x = pi/4
  Numerical : 0.70710678
  Exact     : 0.70710678
  Error     : 1.40e-11


### 1.3 Effect of the Step Size $h$
The central-difference formula is $O(h^2)$: smaller $h$ gives higher accuracy, but very small values eventually cause floating-point cancellation error.


In [17]:
x0    = 3.0
exact = 2 * x0  # d/dx x^2 at x = 3

print(f"{'h':>12}  {'numerical':>14}  {'abs error':>12}")
print("-" * 44)
for exp in range(-1, -16, -1):
    h   = 10**exp
    val = derivative(lambda x: x**2, x0, h=h)
    err = abs(val - exact)
    print(f"  1e{exp:+03d}      {val:14.8f}  {err:12.2e}")


           h       numerical     abs error
--------------------------------------------
  1e-01          6.00000000      5.33e-15
  1e-02          6.00000000      1.28e-13
  1e-03          6.00000000      6.61e-13
  1e-04          6.00000000      1.27e-11
  1e-05          6.00000000      3.93e-11
  1e-06          6.00000000      8.39e-10
  1e-07          5.99999999      9.82e-09
  1e-08          5.99999996      3.65e-08
  1e-09          6.00000050      4.96e-07
  1e-10          6.00000050      4.96e-07
  1e-11          6.00000050      4.96e-07
  1e-12          6.00053340      5.33e-04
  1e-13          6.00408612      4.09e-03
  1e-14          6.12843110      1.28e-01
  1e-15          5.32907052      6.71e-01


---
## 2. `derivative` — Vector-Valued Functions ($\mathbb{R} \to \mathbb{R}^n$)

When $f$ returns a NumPy array, `derivative` returns the component-wise derivative vector.

### 2.1 $f(x) = [x^2,\; x^3]$
Exact: $f'(x) = [2x,\; 3x^2]$, so at $x = 2.0$ we expect $[4.0,\; 12.0]$.


In [18]:
v_f = lambda x: np.array([x**2, x**3])

x0        = 2.0
numerical = derivative(v_f, x0)
exact     = np.array([2 * x0, 3 * x0**2])

print(f"f(x) = [x^2, x^3]  at  x = {x0}")
print(f"  Numerical : {numerical}")
print(f"  Exact     : {exact}")
print(f"  Error     : {np.abs(numerical - exact)}")


f(x) = [x^2, x^3]  at  x = 2.0
  Numerical : [ 4. 12.]
  Exact     : [ 4. 12.]
  Error     : [2.62048161e-11 2.11839435e-10]


### 2.2 $f(x) = [\sin(x),\; \cos(x),\; e^x]$
Exact: $f'(x) = [\cos(x),\; -\sin(x),\; e^x]$ at $x = 1.0$.


In [19]:
v_f = lambda x: np.array([np.sin(x), np.cos(x), np.exp(x)])

x0        = 1.0
numerical = derivative(v_f, x0)
exact     = np.array([np.cos(x0), -np.sin(x0), np.exp(x0)])

print(f"f(x) = [sin(x), cos(x), exp(x)]  at  x = {x0}")
print(f"  Numerical : {numerical}")
print(f"  Exact     : {exact}")
print(f"  Max error : {np.max(np.abs(numerical - exact)):.2e}")


f(x) = [sin(x), cos(x), exp(x)]  at  x = 1.0
  Numerical : [ 0.54030231 -0.84147098  2.71828183]
  Exact     : [ 0.54030231 -0.84147098  2.71828183]
  Max error : 5.86e-11


---
## 3. `partial_derivative` — Multivariate Functions ($\mathbb{R}^n \to \mathbb{R}$ or $\mathbb{R}^n \to \mathbb{R}^m$)

`partial_derivative(f, v_x, idx, h)` computes $\partial f / \partial x_{\text{idx}}$ by perturbing only the `idx`-th component of the input vector.

### 3.1 Scalar Output: $f(x, y) = x^2 \cdot y$
Exact partial derivatives:
- $\partial f / \partial x = 2xy$ at $[2, 3]$: expected $12$
- $\partial f / \partial y = x^2$ at $[2, 3]$: expected $4$


In [20]:
s_f = lambda v: v[0]**2 * v[1]  # f(x, y) = x^2 * y
v_x = np.array([2.0, 3.0])

df_dx = partial_derivative(s_f, v_x, idx=0)
df_dy = partial_derivative(s_f, v_x, idx=1)

print(f"f(x, y) = x^2 * y  at  [x, y] = {v_x}")
print(f"  df/dx  Numerical : {df_dx:.8f}  |  Exact : {2 * v_x[0] * v_x[1]:.8f}")
print(f"  df/dy  Numerical : {df_dy:.8f}  |  Exact : {v_x[0]**2:.8f}")


f(x, y) = x^2 * y  at  [x, y] = [2. 3.]
  df/dx  Numerical : 12.00000000  |  Exact : 12.00000000
  df/dy  Numerical : 4.00000000  |  Exact : 4.00000000


### 3.2 Vector Output: $f(x, y) = [x \cdot y,\; x + y^2]$
Exact partial derivatives:
- $\partial f / \partial x = [y,\; 1]$ at $[2, 3]$: expected $[3, 1]$
- $\partial f / \partial y = [x,\; 2y]$ at $[2, 3]$: expected $[2, 6]$


In [21]:
v_f = lambda v: np.array([v[0] * v[1], v[0] + v[1]**2])
v_x = np.array([2.0, 3.0])

df_dx = partial_derivative(v_f, v_x, idx=0)
df_dy = partial_derivative(v_f, v_x, idx=1)

print(f"f(x, y) = [x*y, x + y^2]  at  [x, y] = {v_x}")
print(f"  df/dx  Numerical : {df_dx}  |  Exact : {np.array([v_x[1], 1.0])}")
print(f"  df/dy  Numerical : {df_dy}  |  Exact : {np.array([v_x[0], 2*v_x[1]])}")


f(x, y) = [x*y, x + y^2]  at  [x, y] = [2. 3.]
  df/dx  Numerical : [3. 1.]  |  Exact : [3. 1.]
  df/dy  Numerical : [2. 6.]  |  Exact : [2. 6.]


---
## 4. `v_gradient` — Gradient of a Scalar Field ($\mathbb{R}^n \to \mathbb{R}$)

`v_gradient(s_f, v_x)` returns $\nabla f(\mathbf{x}) = \left[\frac{\partial f}{\partial x_0},\; \frac{\partial f}{\partial x_1},\; \ldots\right]$, computing all partial derivatives at once.

### 4.1 Quadratic Form: $f(x, y, z) = x^2 + y^2 + z^2$
Exact gradient: $\nabla f = [2x, 2y, 2z]$ at $[1, 2, 3]$: expected $[2, 4, 6]$.


In [22]:
s_f = lambda v: v[0]**2 + v[1]**2 + v[2]**2
v_x = np.array([1.0, 2.0, 3.0])

grad       = v_gradient(s_f, v_x)
grad_exact = 2 * v_x

print(f"f(x, y, z) = x^2 + y^2 + z^2  at  {v_x}")
print(f"  grad f  Numerical : {grad}")
print(f"  grad f  Exact     : {grad_exact}")
print(f"  Max error         : {np.max(np.abs(grad - grad_exact)):.2e}")


f(x, y, z) = x^2 + y^2 + z^2  at  [1. 2. 3.]
  grad f  Numerical : [2. 4. 6.]
  grad f  Exact     : [2. 4. 6.]
  Max error         : 1.02e-10


### 4.2 Mixed Terms: $f(x, y) = x^2 y + \sin(x) e^y$
Exact gradient:
- $\partial f / \partial x = 2xy + \cos(x) e^y$
- $\partial f / \partial y = x^2 + \sin(x) e^y$


In [23]:
s_f = lambda v: v[0]**2 * v[1] + np.sin(v[0]) * np.exp(v[1])
v_x = np.array([1.0, 0.5])

grad = v_gradient(s_f, v_x)
grad_exact = np.array([
    2 * v_x[0] * v_x[1] + np.cos(v_x[0]) * np.exp(v_x[1]),
    v_x[0]**2 + np.sin(v_x[0]) * np.exp(v_x[1]),
])

print(f"f(x, y) = x^2*y + sin(x)*exp(y)  at  {v_x}")
print(f"  grad f  Numerical : {grad}")
print(f"  grad f  Exact     : {grad_exact}")
print(f"  Max error         : {np.max(np.abs(grad - grad_exact)):.2e}")


f(x, y) = x^2*y + sin(x)*exp(y)  at  [1.  0.5]
  grad f  Numerical : [1.8908079  2.38735111]
  grad f  Exact     : [1.8908079  2.38735111]
  Max error         : 2.50e-11


---
## 5. `divergence` — Divergence of a Vector Field ($\mathbb{R}^n \to \mathbb{R}^n$)

`divergence(v_f, v_x)` computes the scalar $\nabla \cdot \mathbf{F}(\mathbf{x}) = \sum_i \frac{\partial F_i}{\partial x_i}$.

**Note:** The input and output of `v_f` must have the same dimension.

### 5.1 Linear Field: $\mathbf{F}(x, y) = [x,\; y]$
Exact: $\nabla \cdot \mathbf{F} = 1 + 1 = 2$ (constant everywhere).


In [24]:
v_f = lambda v: np.array([v[0], v[1]])

for point in [np.array([1.0, 0.0]), np.array([3.0, -2.0]), np.array([0.0, 0.0])]:
    div = divergence(v_f, point)
    print(f"  At {point}: div F = {div:.6f}  (exact = 2.0)")


  At [1. 0.]: div F = 2.000000  (exact = 2.0)
  At [ 3. -2.]: div F = 2.000000  (exact = 2.0)
  At [0. 0.]: div F = 2.000000  (exact = 2.0)


### 5.2 Quadratic Field: $\mathbf{F}(x, y, z) = [x^2,\; y^2,\; z^2]$
Exact: $\nabla \cdot \mathbf{F} = 2x + 2y + 2z$ at $[1, 1, 1]$: expected $6$.


In [25]:
v_f = lambda v: np.array([v[0]**2, v[1]**2, v[2]**2])

test_points = [
    (np.array([1.0, 1.0, 1.0]), 6.0),
    (np.array([2.0, 3.0, 4.0]), 18.0),
    (np.array([0.0, 0.0, 0.0]), 0.0),
]

print(f"F(x,y,z) = [x^2, y^2, z^2]  ->  div F = 2x + 2y + 2z")
print(f"{'Point':>20}  {'Numerical':>12}  {'Exact':>8}  {'Error':>10}")
print("-" * 58)
for point, exact in test_points:
    div = divergence(v_f, point)
    print(f"  {str(point):>18}  {div:12.6f}  {exact:8.1f}  {abs(div - exact):10.2e}")


F(x,y,z) = [x^2, y^2, z^2]  ->  div F = 2x + 2y + 2z
               Point     Numerical     Exact       Error
----------------------------------------------------------
          [1. 1. 1.]      6.000000       6.0    6.00e-12
          [2. 3. 4.]     18.000000      18.0    1.49e-10
          [0. 0. 0.]      0.000000       0.0    0.00e+00


### 5.3 Rotational Field: $\mathbf{F}(x, y) = [-y,\; x]$
This is a purely rotational (curl) field. Its divergence is exactly $0$ everywhere:
$\partial(-y)/\partial x + \partial x/\partial y = 0 + 0 = 0$.


In [26]:
v_f = lambda v: np.array([-v[1], v[0]])  # Rotational (curl) field

for point in [np.array([1.0, 0.0]), np.array([2.0, 3.0]), np.array([-1.0, 5.0])]:
    div = divergence(v_f, point)
    print(f"  At {point}: div F = {div:.2e}  (exact = 0.0)")


  At [1. 0.]: div F = 0.00e+00  (exact = 0.0)
  At [2. 3.]: div F = 0.00e+00  (exact = 0.0)
  At [-1.  5.]: div F = 0.00e+00  (exact = 0.0)
